### ISSUE TITLE
【Question】json data check failed using sync_diff_inspector;

### ISSUE THREAD

**Issue by jianhaiqing** [pingcap/tidb-tools#124]
`json data doesn't replicate with correct order using syncer.`

* show create table 

```
CREATE TABLE `dynamic` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uid` varchar(32) NOT NULL COMMENT '业务uid',
  `type` int(11) NOT NULL DEFAULT '1' ,
  `title` varchar(256) NOT NULL DEFAULT '' COMMENT '标题',
  `content` varchar(8192) DEFAULT NULL,
  `picture_url` varchar(2048) NOT NULL DEFAULT '' COMMENT '图片地址字符串，多个地址用","分隔',
  `audio_url` varchar(128) NOT NULL DEFAULT '' COMMENT '音频url',
  `audio_duration` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '音频时长',
  `web_content` varchar(1024) NOT NULL DEFAULT '' COMMENT '外链内容',
  `need_reply` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要回复，0是不需要，1是需要',
  `reply_expired_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复截止时间',
  `show_role` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '可见的角色',
  `creator_uid` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者uid',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标识',
  `like_count` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '点赞数',
  `audios` json DEFAULT NULL COMMENT '存储音频列表',
  `videos` json DEFAULT NULL COMMENT '存储视频列表',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uid` (`uid`) USING BTREE,
  KEY `idx_type` (`type`)
) ENGINE=InnoDB AUTO_INCREMENT=5542058 DEFAULT CHARSET=utf8;
```

* checking failed data due to column audios

- source from mysql

```
id: 5541955
               uid: 3b047b3fe8604026ac12084770e2a609
              type: 1
             title: 111
           content: 555
       picture_url:
         audio_url:
    audio_duration: 0
       web_content:
        need_reply: 1
reply_expired_time: 2018-11-16 11:03:46
         show_role: 1
       creator_uid: ced40d39cc0a4d23a28f47c4d218e5a0
        created_at: 2018-11-16 11:03:24
        updated_at: 2018-11-16 11:03:24
        is_deleted: 0
        like_count: 0
            audios: [{"audioUrl": "111", "audioDuration": 111}]
            videos: NULL
```

- target from tidb

```
id: 5541955
               uid: 3b047b3fe8604026ac12084770e2a609
              type: 1
             title: 111
           content: 555
       picture_url:
         audio_url:
    audio_duration: 0
       web_content:
        need_reply: 1
reply_expired_time: 2018-11-16 11:03:46
         show_role: 1
       creator_uid: ced40d39cc0a4d23a28f47c4d218e5a0
        created_at: 2018-11-16 11:03:24
        updated_at: 2018-11-16 11:03:24
        is_deleted: 0
        like_count: 0
            audios: [{"audioDuration": 111, "audioUrl": "111"}]
            videos: NULL
```

* MySQL master version (percona server) :
```
Connection id:		73439
Current database:	xxx
Current user:		root@10.10.12.116
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.19-17-log Source distribution
Protocol version:	10
Connection:		10.10.12.116 via TCP/IP
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
TCP port:		3306
Uptime:			50 days 15 hours 13 min 39 sec
```

* tidb_version:
```
Release Version: v2.0.7
Git Commit Hash: 29ec059
Git Branch: release-2.0
UTC Build Time: 2018-09-07 12:36:02
GoVersion: go version go1.11 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1

Release Version: v1.0.0-48-g4ac1cfc
Git Commit Hash: 4ac1cfc7c1f9ac256c37733d831ce7dd1643b3fa
Git Branch: master
UTC Build Time: 2018-11-15 09:15:13
Go Version: go version go1.11 linux/amd64
```
