### ISSUE TITLE
sync-diff-inspector: mysql to mysql check error

### ISSUE THREAD

**Issue by teckick** [pingcap/tidb-tools#558]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Create two databases and tables in one MySQL instance.

```
CREATE DATABASE inspector_mysql_0;
CREATE TABLE inspector_mysql_0.tb_emp1 (id INT(11), name VARCHAR(25), deptId INT(11));
INSERT INTO inspector_mysql_0.tb_emp1 values (1,"hello1",1);
CREATE DATABASE inspector_mysql_1;
CREATE TABLE inspector_mysql_1.tb_emp1 (id INT(11), name VARCHAR(25), deptId INT(11));
INSERT INTO inspector_mysql_1.tb_emp1 values (1,"hello1",1);
```

then run sync-diff-inspector with config.toml

```toml
# Diff Configuration.

######################### Global config #########################

# how many goroutines are created to check data
check-thread-count = 4

# set false if just want compare data by checksum, will skip select data when checksum is not equal.
# set true if want compare all different rows, will slow down the total compare time.
export-fix-sql = true

# ignore check table's data
check-struct-only = false


######################### Databases config #########################
[data-sources.mysql1]
    host = "127.0.0.1"
    port = 3306
    user = "root"
    password = "12344321"
    route-rules = ["rule1"]

[data-sources.tidb0]
    host = "127.0.0.1"
    port = 3306
    user = "root"
    password = "12344321"
    # remove comment if use tidb's snapshot data

[routes.rule1]
schema-pattern = "inspector_mysql_0"      # schema to match. Support wildcard characters * and ?.
table-pattern = "tb_emp1"          # table to match. Support wildcard characters * and ?.
target-schema = "inspector_mysql_1"         # target schema
target-table = "tb_emp1"             # target table

######################### Task config #########################
# Required
[task]
    # 1 fix sql: fix-target-TIDB1.sql
    # 2 log: sync-diff.log
    # 3 summary: summary.txt
    # 4 checkpoint: a dir
    output-dir = "/tmp/output/config"

    source-instances = ["mysql1"]

    target-instance = "tidb0"

    # tables need to check. *Include `schema` and `table`. Use `.` to split*
    target-check-tables = ["inspector_mysql_1.tb_emp1"]

    # extra table config
#     target-configs= []
    target-configs= ["config1"]

# Optional
# [table-configs]
[table-configs.config1]

# tables need to use this specified config.
# if use this config. target-tables should be a subset of #target-check-tables
target-tables = ["inspector_mysql_1.tb_emp1"]

range = "id > 0"
index-fields = [""]
ignore-columns = ["",""]
chunk-size = 0
collation = ""
```

2. What did you expect to see?

```
The table structure and data in following tables are equivalent

`inspector_mysql_1`.`tb_emp1`
```

3. What did you see instead?

```
The table structure and data in following tables are equivalent


The following tables contains inconsistent data

+-------------------------------+--------------------+----------------+
|             TABLE             | STRUCTURE EQUALITY | DATA DIFF ROWS |
+-------------------------------+--------------------+----------------+
| `inspector_mysql_1`.`tb_emp1` | true               | +1/-0          |
+-------------------------------+--------------------+----------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

MySQL 8.0.22

5. which tool are you using?

tidb-tools/sync-diff-inspector

6. what version of tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

```
App Name: sync_diff_inspector v2.0
Release Version: v5.2.2-113-g39e3eb4-dirty
Git Commit Hash: 39e3eb4bb9725bf714bd6c23a77de69852ea2a27
Git Branch: master
UTC Build Time: 2021-11-28 07:25:14
Go Version: go1.17
```

**Comment by Leavrth** [comment]
We have rule pattern in the config like this,
```toml
[rule1]
schema-pattern = "schema*"  # schema to match. Support wildcard characters * and ?.
table-pattern = "table_*"   # table to match. Support wildcard characters * and ?.
target-schema = "schema"    # target schema
target-table = "table"      # target table
```
For the above rule, we can say that **the rule matches `schema2.table_3 -> schema.table`**

**The initialization of table router now do like this:**
1. given a `target-schema/target-table` table named `schema.table` in the rules
a. If there is a rule matches `schema.table -> schema.table`, do nothing.
b. If there is not rule matches `schema.table -> schema.table`, we think the config wants to mask this match, so we add a new rule `schema.table -> _no__exists__db_._no__exists__table_` to the table router. After that, sync-diff-inspector will regard table `schema.table` as table `_no__exists__db_._no__exists__table_` instead of itself.
2. given a `target-schema` only in the rules, such like:
```toml
[rule1]
schema-pattern = "schema_*"  # schema to match. Support wildcard characters * and ?.
target-schema = "schema"    # target schema
```
a. Ditto 1.a, do nothing.
b. If there is not rule matches `schema -> schema`, we think the config wants to mask this match, so we add a new rule `schema -> _no__exists__db_` to the table router. After that, sync-diff-inspector will regard table `schema` as table `_no__exists__db_` instead of itself.

3. `target-schema.target-table` does not exist in the rules.
we add the rule `target-schema.target-table -> target-schema.target-table` to make it case-insensitive (**that's because the table router is case-insensitive**).

================================================

**We have some examples.** Suppose there are seven tables, which are `inspector_mysql_0`.`tb_emp1`, `Inspector_mysql_0`.`tb_emp1`, `inspector_mysql_0`.`Tb_emp1`, `inspector_mysql_1`.`tb_emp1`, `Inspector_mysql_1`.`tb_emp1`, `inspector_mysql_1`.`Tb_emp1` and `Inspector_mysql_1`.`Tb_emp1`.
 
**In config**, upstream has `rule1`, and target table is [`inspector_mysql_1`.`tb_emp1`].
 
1. **If:** 
```toml
[Source.rule1]
schema-pattern = "inspector_mysql_0"
table-pattern = "tb_emp1"
target-schema = "inspector_mysql_1"
target-table = "tb_emp1"
```

regard `inspector_mysql_0`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Inspector_mysql_0`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_0`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_1`.`tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
regard `Inspector_mysql_1`.`tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
regard `inspector_mysql_1`.`Tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
regard `Inspector_mysql_1`.`Tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
 
 
 2. **If:** 
```toml
[Source.rule1]
schema-pattern = "inspector_mysql_0"
target-schema = "inspector_mysql_1"
```

regard `inspector_mysql_0`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Inspector_mysql_0`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_0`.`Tb_emp1` as `inspector_mysql_1`.`Tb_emp1`
regard `inspector_mysql_1`.`tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
regard `Inspector_mysql_1`.`tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
regard `inspector_mysql_1`.`Tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
regard `Inspector_mysql_1`.`Tb_emp1` as `_no__exists__db_`.`_no__exists__table_`
 
3. **If:** 
```toml
[Source.rule1]
schema-pattern = "other_schema"
target-schema = "other_schema"
```
regard `inspector_mysql_0`.`tb_emp1` as `inspector_mysql_0`.`tb_emp1`
regard `Inspector_mysql_0`.`tb_emp1` as `Inspector_mysql_0`.`tb_emp1`
regard `inspector_mysql_0`.`Tb_emp1` as `inspector_mysql_0`.`Tb_emp1`
regard `inspector_mysql_1`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Inspector_mysql_1`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_1`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Tnspector_mysql_1`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
 
4. **If.** no rules

regard `inspector_mysql_0`.`tb_emp1` as `inspector_mysql_0`.`tb_emp1`
regard `Inspector_mysql_0`.`tb_emp1` as `Inspector_mysql_0`.`tb_emp1`
regard `inspector_mysql_0`.`Tb_emp1` as `inspector_mysql_0`.`Tb_emp1`
regard `inspector_mysql_1`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Inspector_mysql_1`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_1`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Tnspector_mysql_1`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
 
5. **If:**
```toml
[Source.rule1]
schema-pattern = "inspector_mysql_?"
table-pattern = "tb_emp1"
target-schema = "inspector_mysql_1"
target-table = "tb_emp1"
```

regard `inspector_mysql_0`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Inspector_mysql_0`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_0`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_1`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Inspector_mysql_1`.`tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `inspector_mysql_1`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
regard `Tnspector_mysql_1`.`Tb_emp1` as `inspector_mysql_1`.`tb_emp1`
