### ISSUE TITLE
sync-diff hint is not clear: matches 2 table route rules which is more than one

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tidb-tools#571]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

- For sync-diff 5.3.0 , it seems the config in route-rules(routes) and Task config (target-check-tables) may have conflict setting, but the document or sync diff log is not very clear message when user has this mistake. 

2. What did you expect to see?

- Document has something like: Please make sure route-rules(routes) and Task config (target-check-tables) has not repeated setting.

3. What did you see instead?
[2021/12/20 15:40:20.421 +08:00] [FATAL] [main.go:95] ["failed to initialize diff process"] [error="from upstream: get route result for betting_0.unit1_5_game_bets_game_tag_0 failed, error `betting_0`.`unit1_5_game_bets_game_tag_0` matches 2 table route rules which is more than one.\nThe first two rules are &{SchemaPattern:betting_0 TablePattern:unit1_* TargetSchema:betting_0 TargetTable:unit1_* TableExtractor:<nil> SchemaExtractor:<nil> SourceExtractor:<nil>}, &{SchemaPattern:betting_0 TablePattern:unit1_5_game_bets_game_tag_0 TargetSchema:betting_0 TargetTable:unit1_5_game_bets_game_tag_0 TableExtractor:<nil> SchemaExtractor:<nil> SourceExtractor:<nil>}.\nIt's not supported"]

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by Leavrth** [comment]
This is because there is a table can match 2 rules, such as config:

```toml
[routes]
[routes.rule1]
schema-pattern = "betting_0"
table-pattern = "unit1_*"
target-schema = "betting_0"
target-table = "unit1_*"

[routes.rule2]
schema-pattern = "betting_0"
table-pattern = "unit1_5_game_bets_game_tag_0"
target-schema = "betting_0"
target-table = "unit1_5_game_bets_game_tag_0"
```
