### ISSUE TITLE
sync-diff-inspector: index-fields does not take effect if bucket stats are used.

### ISSUE THREAD

**Issue by liuzix** [pingcap/tidb-tools#623]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
root@sbtest[v5]> show create table sbtest1 \G
*************************** 1. row ***************************
       Table: sbtest1
Create Table: CREATE TABLE `sbtest1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `k` int(11) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=10407284
1 row in set (0.00 sec)
```

```toml
# Diff Configuration.
######################### Global config #########################
check-thread-count = 4
export-fix-sql = true
check-struct-only = false


######################### Datasource config #########################
[data-sources]
[data-sources.upstream]
    host = "upstream-host"
    port = 4000
    user = "root"
    password = ""
    #snapshot = "433361056758235137"

[data-sources.downstream]
    host = "downstream-host"
    port = 5300
    user = "root"
    password = ""
    #snapshot = "433361057203093509"

######################### Task config #########################
[task]
    output-dir = "./output5"
    source-instances = ["upstream"]
    target-instance = "downstream"
    target-check-tables = ["sbtest.sbtest1"]
    target-configs = ["config1"]

######################### Table config #########################
[table-configs.config1]
target-tables = ["sbtest.sbtest1"]
#range = "age > 10 AND age < 20"
index-fields = ["k"]
#ignore-columns = [""]
chunk-size = 50000
#collation = ""

```

2. What did you expect to see?
- The key `k_1` should be used to split chunks.

3. What did you see instead?
- The primary key is used instead.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Irrelevant.

6. which tool are you using?
sync-diff-inspector

7. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?
`v5.4.1`.
