### ISSUE TITLE
sync-diff-inspector: auto position tidb_snapshot from last syncpoint

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb-tools#663]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently sync-diff-inspector does not support checking streams that are actively being read/written from. This is a problem, since it can't be used for TiCDC consistency checking. There is a FR to do online checksumming here: https://github.com/pingcap/dm/issues/1097

However, if the source and destination are TiDB this is not the best way to do this. Instead, syncpoint (experimental) can be used. The source and destination can be set to use a tidb_snapshot to consistently compare.

**Describe the feature you'd like:**

My feature request is to "auto position" the `snapshot` which is used to compare, based on reading the most recently entry from the syncpoint table.

For example, given the following config:

```toml
######################### Databases config #########################
[data-sources]
[data-sources.tidb1]
    host = "127.0.0.1"
    port = 4000
    user = "root"
    password = ""
    snapshot = "auto"

[data-sources.tidb2]
    host = "192.168.86.38"
    port = 4000
    user = "root"
    password = ""
    snapshot = "auto"

######################### Task config #########################
# Required
[task]
    # 1 fix sql: fix-target-TIDB1.sql
    # 2 log: sync-diff.log
    # 3 summary: summary.txt
    # 4 checkpoint: a dir
    output-dir = "/tmp/output/config"

    source-instances = ["tidb1"]

    target-instance = "tidb2"

    # tables need to check. *Include `schema` and `table`. Use `.` to split*
    target-check-tables = ["test.stock"]

    # extra table config
    target-configs= ["config1"]
```

sync-diff-inspector will automatically run the following query on `target-instance` and apply primary_ts to source and secondary_ts to target.

```sql
tidb> select primary_ts, secondary_ts  from tidb_cdc.syncpoint_v1 order by primary_ts desc limit 1;
+--------------------+--------------------+
| primary_ts         | secondary_ts       |
+--------------------+--------------------+
| 434722879294406656 | 434723226951352321 |
+--------------------+--------------------+
1 row in set (0.00 sec)
```

This will save a lot of config file editing.

**Describe alternatives you've considered:**

The alternative is to generate config files each time to use for compare.  But it's a pretty straight forward use case so I'm hoping support can be built in.

**Teachability, Documentation, Adoption, Migration Strategy:**
